changeLogFile=master-changelog.yaml

# Connexion MySQL (depuis ton host)
url=jdbc:mysql://localhost:3306/school_db
username: school_user
password: school_pass

# Driver JDBC
classpath=mysql-connector-j-8.3.0.jar
driver=com.mysql.cj.jdbc.Driver
